name: CI/CD for React App

on:
  push:
    branches: [main]
  release:
    types: [published]

env:
  CI: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./build

  deploy:
    name: "Deploy to Netlify"
    runs-on: ubuntu-latest

    steps:
      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.nfp_4y9eiyvCYq8yGfjYqX8bg4BMW5v4HJXk1829 }}
          NETLIFY_DEPLOY_TO_PROD: true
