name: CI/CD for React App

on:
  push:
    branches: [main]
  release:
    types: [published]

env:
  CI: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./build

  deploy:
    name: Deploy to Netlify
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download production-ready build files
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          args: deploy --dir=./build --prod
        env:
          NETLIFY_AUTH_TOKEN: "nfp_4y9eiyvCYq8yGfjYqX8bg4BMW5v4HJXk1829"
          NETLIFY_SITE_ID: "84c6b2bb-d8f8-43a0-aa34-be572b887965"
